### PR TITLE
rename decorators: async -> getAsync, resolver -> resolvedBy (fixes #52)

### LINKED ISSUE #52: Rename resolver to resolveWith or resolveBy
```
class Thing extends observe.Object {
  @observe.resolvedBy
  foo( {listenTo, resolve } ){
    
  }
}
```

### PR DESCRIPTION
**Pull request by christopherjbaker**

### CODE REVIEW

**Review by justinbmeyer — CHANGES_REQUESTED** [review]
Lets not break the old apis.  Can you leave them in for compatibility?

I'm not sure how I feel about `getAsync`.  Why did that change?

**Comment by christopherjbaker** [comment]
[Both of the originals were left in and deprecated](https://github.com/canjs/can-observe/blob/2db0539e8448e121b80d199b226301b3efe6ab0c/decorators/decorators.js#L136-L155)

I changed `async` because its present form cannot be imported as a named import, due to the new-ish async functions. I have no connection to `getAsync`, I just figured this was a good time to change it as we were changing the other.

**Comment by justinbmeyer** [comment]
Ah, I missed the part where you left them in.  Lets brainstorm a bit on these names. One problem with `resolveBy` and `getAsync` is they both are really resolved by calling `resolve`.  _Why aren't they both called `resolveBy`?_ The difference is that:

- `getAsync` will form a "compute" around the function, implicitly binding on all read observables (And I think you made it take promises too)
- `resolveBy` you have to do the binding yourself

@chasenlehara and @phillipskevin should be involved in this because `can-value` will likely have these methods too, we should try to be consistent everywhere.  Relevant issue:

https://github.com/canjs/can-value/issues/5

Some options:

- basic getter: `value.get()` `value.returnedBy()` `value.compute()`
- async getter: `value.getAsync()` `value.asyncGet()` `value.asyncResolve()` `value.resolveAsync()`
- binder: `value.resolvedBy()`, `value.resolvedWith()`

Best might be:

```js
value.returnedBy()
value.resolveAsync()
value.resolvedBy()
```

idk ... I'm very open to suggestions ...


Another:

```js
value.compute( handler() )
value.asyncCompute( handler(resolve) )
value.resolve( handler( {listenTo, lastSet, resolve, stopListening} ) )
```

**Comment by chasenlehara** [comment]
I don’t feel strongly about this, but I would lean toward what Justin’s proposing, with the exception that I would call it either `resolvedByAsync` or `resolvedAsync`.

**Comment by BigAB** [comment]
Is this accurate:

basic getter:  is analogous to a synchronous get
async getter: is analogous to an asynchronous get, like 1 promise, 1 value to return
binder: is analogous to a stream, from 1 dependancy change could produce 0 - many values

If this is accurate I like:
- basic getter: `value.get()`
- async getter: `value.getAsync()`
- binder: `value.resolvedBy()`

**Pull request closed without merging**
